/** @type {import('tailwindcss').Config} */

const config = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "var(--tertiary-container)",
        "on-surface": "var(--on-surface)",
        background: "var(--background)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "inverse-primary": "var(--inverse-primary)",
        "error-container": "var(--error-container)",
        surface: "var(--surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-dim": "var(--surface-dim)",
        "on-primary": "var(--on-primary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        tertiary: "var(--tertiary)",
        "on-error": "var(--on-error)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "secondary-container": "var(--secondary-container)",
        primary: "var(--primary)",
        "surface-container": "var(--surface-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-bright": "var(--surface-bright)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "inverse-surface": "var(--inverse-surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-background": "var(--on-background)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-secondary": "var(--on-secondary)",
        outline: "var(--outline)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        secondary: "var(--secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-tint": "var(--surface-tint)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "on-error-container": "var(--on-error-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-low": "var(--surface-container-low)",
        "primary-container": "var(--primary-container)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        error: "var(--error)",
        "surface-variant": "var(--surface-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "border-width-ornamental": "4px",
        gutter: "24px",
        margin: "32px",
        "border-width-thin": "1px",
        "container-max": "1200px",
      },
      screens: {
        "container-max": "1200px",
      },
      fontFamily: {
        "body-lg": ["var(--font-newsreader)", "Newsreader", "serif"],
        "label-sm": ["var(--font-newsreader)", "Newsreader", "serif"],
        "headline-md": ["var(--font-cinzel)", "Cinzel", "serif"],
        "headline-xl": ["var(--font-cinzel)", "Cinzel", "serif"],
        "headline-lg": ["var(--font-cinzel)", "Cinzel", "serif"],
        "body-md": ["var(--font-newsreader)", "Newsreader", "serif"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
